<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="android.ninetynine.ldp.enquiry.C1351_LDP_NoAcc_Reg_PhoneEnquiry" tests="1" time="126.203" ignored="0" failures="1" timestamp="29 Dec 2020 12:40:54 GMT" skipped="0" hostname="daniamrth" errors="0">
  <testcase name="C1351_LDP_NoAcc_Reg_Phone_Enquiry" time="126.203" classname="android.ninetynine.ldp.enquiry.C1351_LDP_NoAcc_Reg_PhoneEnquiry">
    <failure type="java.lang.AssertionError" message="Object not found step failed">
      <![CDATA[java.lang.AssertionError: Object not found step failed
	at org.testng.Assert.fail(Assert.java:94)
	at android.ninetynine.util.GeneralUtilities.verifyelemen(GeneralUtilities.java:51)
	at android.ninetynine.util.GeneralUtilities.click(GeneralUtilities.java:60)
	at android.ninetynine.pageobjects.SearchResultPage.Click_Srp_Reg_List(SearchResultPage.java:61)
	at android.ninetynine.ldp.enquiry.C1351_LDP_NoAcc_Reg_PhoneEnquiry.C1351_LDP_NoAcc_Reg_Phone_Enquiry(C1351_LDP_NoAcc_Reg_PhoneEnquiry.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- C1351_LDP_NoAcc_Reg_Phone_Enquiry -->
</testsuite> <!-- android.ninetynine.ldp.enquiry.C1351_LDP_NoAcc_Reg_PhoneEnquiry -->
